name: true_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.3+1
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Arial
      fonts:
        - asset: fonts/Arial/ArialRegular.ttf
        - asset: fonts/Arial/ArialItalic.ttf
          style: italic
        - asset: fonts/Arial/ArialRegular.ttf
          weight: 700
