name: true_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.3+4
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+2
  flutter_bloc: ^0.21.0
  equatable: ^0.6.1
  easy_localization: ^1.3.1
  circular_profile_avatar: ^1.0.2
  rxdart: ^0.22.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/icon.png"
  image_path_android: "assets/images/launcher/icon.png"
  adaptive_icon_background: "assets/images/launcher/background.png"
  adaptive_icon_foreground: "assets/images/launcher/foreground.png"


flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Arial
      fonts:
        - asset: fonts/Arial/ArialRegular.ttf
        - asset: fonts/Arial/ArialItalic.ttf
          style: italic
        - asset: fonts/Arial/ArialRegular.ttf
          weight: 700

  assets:
    - assets/images/logo_icon.png
